# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: downloading ubuntu-16.04.1-server-amd64.iso
  get_url:
    url: http://mirror.csclub.uwaterloo.ca/ubuntu-releases/16.04.1/ubuntu-16.04.1-server-amd64.iso
    dest: /home/{{ regular_system_user }}/svauto/downloads/ubuntu-16.04.1-server-amd64.iso
    mode: 0640

- name: downloading ubuntu-14.04.5-server-amd64.iso
  get_url:
    url: http://mirror.csclub.uwaterloo.ca/ubuntu-releases/14.04.5/ubuntu-14.04.5-server-amd64.iso
    dest: /home/{{ regular_system_user }}/svauto/downloads/ubuntu-14.04.5-server-amd64.iso
    mode: 0640

- name: downloading CentOS-7-x86_64-Minimal-1511.iso
  get_url:
    url: http://mirror.its.sfu.ca/mirror/CentOS/7.2.1511/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso
    dest: /home/{{ regular_system_user }}/svauto/downloads/CentOS-7-x86_64-Minimal-1511.iso
    mode: 0640

- name: downloading CentOS-6.8-x86_64-minimal.iso
  get_url:
    url: http://mirror.its.sfu.ca/mirror/CentOS/6.8/isos/x86_64/CentOS-6.8-x86_64-minimal.iso
    dest: /home/{{ regular_system_user }}/svauto/downloads/CentOS-6.8-x86_64-minimal.iso
    mode: 0640
